### ISSUE TITLE
多用户登录

### ISSUE THREAD

**Issue by qiuhongxiao** [TingYinHelen/helen-robot#2]
请问支持多用户登录吗？我把这个项目整合到一个http服务里，当一个用户请求后扫码登录没问题，另外一个用户再请求，前面一个用户就会被下线（syncCheck检测到退出），不知道是代码问题还是微信的限制, 我已经把Core改为支持多线程，服务端能区分不同用户用的是哪个Core,

**Comment by Glowdable** [comment]
这个是代码设计，我的设计目的就是只支持一个用户，扫码登录。我这边暂时没有多个用户登录的需求，如果你有这个需求，可以提交pr，或者自行实现
